### PR TITLE
Fix fuzzy search over marks with telescope

### LINKED ISSUE #11: Enable general fuzzy search for marks with telescope
When I run `:Telescope recall` to put all my project global marks into a telescope picker I can't seem to do a fuzzy search over the results by just typing out say a filename (no results appear). I did find out that the search only seems to care about the mark name, so if I input `A` it will limit the results to the `A` global mark.

### PR DESCRIPTION
**Pull request by Danthewaann**
Fixes #11 

The `ordinal` value should be the same as the `display` value to support fuzzy search.

I also added some extra info (mark character and line number) to each entry to make them more unique incase you have multiple marks set in a single file e.g. `A:/Users/me/Workspace/notes.md:1`.

### CODE REVIEW

File: lua/recall/telescope.lua [hunk 1]
```diff
@@ -19,7 +19,7 @@ M.extension = function(opts)
   local function display_entry(entry)
     return entry_layout({
       { config.opts.sign, config.opts.sign_highlight },
-      entry.value.info.file,
+      entry.value.char .. ":" .. entry.value.info.file .. ":" .. entry.value.info.pos[2]
```
Comment (fnune) [inline lua/recall/telescope.lua]: Instead of indexing into `info.pos`, can we destructure? I believe this works in Lua:

```lua
local _, lnum, col = unpack(entry.info.pos)
```

And then this becomes more readable:
```suggestion
      entry.value.char .. ":" .. entry.value.info.file .. ":" .. lnum
```

File: lua/recall/telescope.lua [hunk 2]
```diff
@@ -31,7 +31,7 @@ M.extension = function(opts)
         return {
           value = entry,
           display = display_entry,
-          ordinal = entry.char,
+          ordinal = entry.char .. ":" .. entry.info.file .. ":" .. entry.info.pos[2],
```
Comment (fnune) [inline lua/recall/telescope.lua]: Ditto (https://github.com/fnune/recall.nvim/pull/12/changes#r2622507284)

**Review by fnune — APPROVED** [review]
Looks good to me, but would appreciate the legibility change if it does work. You can merge once that's done or you find it doesn't work the way I suggested.

**Comment by fnune** [comment]
Looks like I added tests for this :eyes: unexpected.

```
            Passed in:
            (string) 'A'
            Expected:
            (string) 'A:/tmp/nvim-recall-test-47775321633.txt:1'
```

**Comment by fnune** [comment]
@Danthewaann before we merge (and sorry about backtracking): isn't this an absolute path? Should we default to a path relative to Neovim's content root path?

**Comment by Danthewaann** [comment]
> @Danthewaann before we merge (and sorry about backtracking): isn't this an absolute path? Should we default to a path relative to Neovim's content root path?

Do you mean instead of creating test files under `/var` we should create them in a tmp folder in the current working directory instead?

**Comment by fnune** [comment]
I'm suggesting a change in the actual functionality: instead of showing `A:/Users/me/Workspace/notes.md:1` we should show a relative path to the content root, e.g. if Neovim was launched in `/Users/me/Workspace` we would show `A:notes.md:1`.

**Comment by Danthewaann** [comment]
Would doing this break global marks for files that are outside of the directory where neovim was launched? We could check if each file is relative to the current directory before converting it to a relative path. If a file isn't relative to the current directory we still render it as an absolute path so nothing breaks?

**Comment by Danthewaann** [comment]
@fnune I've pushed up commit 296cacc which include the changes to support rendering relative and absolute filenames for marks in telescope. Let me know if it looks reasonable.

**Comment by fnune** [comment]
Lints are failing, but once that's good let's merge?

**Comment by fnune** [comment]
Thanks @Danthewaann !
